//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("libraryModel", "FK_books_avtor", "avtor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(wpf.avtor), "books", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wpf.book), true)]

#endregion

namespace wpf
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class libraryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new libraryEntities object using the connection string found in the 'libraryEntities' section of the application configuration file.
        /// </summary>
        public libraryEntities() : base("name=libraryEntities", "libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new libraryEntities object.
        /// </summary>
        public libraryEntities(string connectionString) : base(connectionString, "libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new libraryEntities object.
        /// </summary>
        public libraryEntities(EntityConnection connection) : base(connection, "libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<avtor> avtors
        {
            get
            {
                if ((_avtors == null))
                {
                    _avtors = base.CreateObjectSet<avtor>("avtors");
                }
                return _avtors;
            }
        }
        private ObjectSet<avtor> _avtors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<book> books
        {
            get
            {
                if ((_books == null))
                {
                    _books = base.CreateObjectSet<book>("books");
                }
                return _books;
            }
        }
        private ObjectSet<book> _books;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the avtors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToavtors(avtor avtor)
        {
            base.AddObject("avtors", avtor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the books EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobooks(book book)
        {
            base.AddObject("books", book);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libraryModel", Name="avtor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class avtor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new avtor object.
        /// </summary>
        /// <param name="id_avtors">Initial value of the id_avtors property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="secondName">Initial value of the secondName property.</param>
        /// <param name="patronymic">Initial value of the patronymic property.</param>
        public static avtor Createavtor(global::System.Int32 id_avtors, global::System.String firstName, global::System.String secondName, global::System.String patronymic)
        {
            avtor avtor = new avtor();
            avtor.id_avtors = id_avtors;
            avtor.firstName = firstName;
            avtor.secondName = secondName;
            avtor.patronymic = patronymic;
            return avtor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_avtors
        {
            get
            {
                return _id_avtors;
            }
            set
            {
                if (_id_avtors != value)
                {
                    Onid_avtorsChanging(value);
                    ReportPropertyChanging("id_avtors");
                    _id_avtors = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_avtors");
                    Onid_avtorsChanged();
                }
            }
        }
        private global::System.Int32 _id_avtors;
        partial void Onid_avtorsChanging(global::System.Int32 value);
        partial void Onid_avtorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String secondName
        {
            get
            {
                return _secondName;
            }
            set
            {
                OnsecondNameChanging(value);
                ReportPropertyChanging("secondName");
                _secondName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("secondName");
                OnsecondNameChanged();
            }
        }
        private global::System.String _secondName;
        partial void OnsecondNameChanging(global::System.String value);
        partial void OnsecondNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String patronymic
        {
            get
            {
                return _patronymic;
            }
            set
            {
                OnpatronymicChanging(value);
                ReportPropertyChanging("patronymic");
                _patronymic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("patronymic");
                OnpatronymicChanged();
            }
        }
        private global::System.String _patronymic;
        partial void OnpatronymicChanging(global::System.String value);
        partial void OnpatronymicChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("libraryModel", "FK_books_avtor", "books")]
        public EntityCollection<book> books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<book>("libraryModel.FK_books_avtor", "books");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<book>("libraryModel.FK_books_avtor", "books", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libraryModel", Name="book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new book object.
        /// </summary>
        /// <param name="id_books">Initial value of the id_books property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static book Createbook(global::System.Int32 id_books, global::System.String name)
        {
            book book = new book();
            book.id_books = id_books;
            book.name = name;
            return book;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_books
        {
            get
            {
                return _id_books;
            }
            set
            {
                if (_id_books != value)
                {
                    Onid_booksChanging(value);
                    ReportPropertyChanging("id_books");
                    _id_books = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_books");
                    Onid_booksChanged();
                }
            }
        }
        private global::System.Int32 _id_books;
        partial void Onid_booksChanging(global::System.Int32 value);
        partial void Onid_booksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private Nullable<global::System.Int32> _year;
        partial void OnyearChanging(Nullable<global::System.Int32> value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_avtor
        {
            get
            {
                return _id_avtor;
            }
            set
            {
                Onid_avtorChanging(value);
                ReportPropertyChanging("id_avtor");
                _id_avtor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_avtor");
                Onid_avtorChanged();
            }
        }
        private Nullable<global::System.Int32> _id_avtor;
        partial void Onid_avtorChanging(Nullable<global::System.Int32> value);
        partial void Onid_avtorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("libraryModel", "FK_books_avtor", "avtor")]
        public avtor avtor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avtor>("libraryModel.FK_books_avtor", "avtor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avtor>("libraryModel.FK_books_avtor", "avtor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<avtor> avtorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<avtor>("libraryModel.FK_books_avtor", "avtor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<avtor>("libraryModel.FK_books_avtor", "avtor", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
